'use strict';
/** فراداده‌ی تنظیمات: برچسب، گروه، نوع (text|textarea|number|bool|select|secret|color|internal) و راهنما */
const GROUPS = { company: 'شرکت', recruitment: 'استخدام', assessment: 'آزمون', sms: 'پیامک و کد تأیید', security: 'امنیت', appearance: 'ظاهر', notifications: 'اعلان‌ها', maintenance: 'نگهداری', system: 'سیستم (داخلی)' };
const T = (group, label, type, help, options) => ({ group, label, type: type || 'text', help: help || '', options: options || null });
const META = {
  company_name: T('company', 'نام کامل شرکت'), company_short_name: T('company', 'نام کوتاه', 'text', 'در پیامک‌ها و عنوان صفحه'), company_slogan: T('company', 'شعار / زیرعنوان'),
  company_phone: T('company', 'تلفن'), company_email: T('company', 'ایمیل'), company_website: T('company', 'وب‌سایت'), company_city: T('company', 'شهر'), company_address: T('company', 'آدرس', 'textarea'),
  company_intro: T('company', 'معرفی کوتاه شرکت (صفحهٔ استخدام)', 'textarea'), company_logo: T('company', 'لوگو', 'internal'), app_url: T('company', 'نشانی عمومی سامانه', 'text', 'مثل https://hr.example.com — برای لینک QR و پیامک‌ها'), timezone_offset: T('company', 'منطقهٔ زمانی', 'text', 'مثل +03:30'),
  recruitment_open: T('recruitment', 'پذیرش درخواست استخدام باز است', 'bool'), recruitment_intro: T('recruitment', 'متن خوشامد صفحهٔ استخدام', 'textarea'), recruitment_closed_text: T('recruitment', 'متن زمان بسته‌بودن پذیرش', 'textarea'),
  recruitment_require_photo: T('recruitment', 'عکس پرسنلی الزامی', 'bool'), recruitment_require_resume: T('recruitment', 'فایل رزومه الزامی', 'bool'), recruitment_allow_edit_after_submit: T('recruitment', 'ویرایش فرم پس از ارسال (تا شروع بررسی)', 'bool'),
  recruitment_duplicate_check: T('recruitment', 'بررسی تکراری‌بودن بر اساس', 'text', 'national_id,mobile'), recruitment_declaration: T('recruitment', 'متن اقرارنامهٔ پایان فرم', 'textarea'), recruitment_thanks_text: T('recruitment', 'پیام پس از ارسال موفق', 'textarea'),
  recruitment_form_code: T('recruitment', 'کد فرم استخدام (چاپ)'), recruitment_tracking_prefix: T('recruitment', 'پیشوند کد پیگیری'), recruitment_draft_days: T('recruitment', 'بایگانی پیش‌نویس‌های رهاشده پس از (روز)', 'number', '۰ = غیرفعال'),
  recruitment_sla_days: T('recruitment', 'هشدار پرونده‌های بررسی‌نشده پس از (روز)', 'number'), recruitment_notify_hr_inapp: T('recruitment', 'اعلان درون‌برنامه‌ای پروندهٔ جدید به تیم HR', 'bool'),
  assessment_form_code: T('assessment', 'کد فرم آزمون (چاپ)'), assessment_required: T('assessment', 'تکمیل آزمون برای متقاضیان الزامی است', 'bool'), assessment_auto_assign: T('assessment', 'تخصیص خودکار آزمون پس از ارسال فرم', 'bool'),
  sms_enabled: T('sms', 'ارسال پیامک فعال', 'bool'), sms_provider: T('sms', 'درگاه پیامک', 'select', '', { log: 'فقط ثبت در لاگ (آزمایشی)', ippanel: 'IPPanel (Edge API)' }), sms_api_key: T('sms', 'کلید API', 'secret', 'پنل IPPanel › توسعه‌دهندگان › کلیدهای دسترسی'),
  sms_sender: T('sms', 'شمارهٔ فرستنده', 'text', 'مثل +983000505'), sms_api_base: T('sms', 'آدرس پایهٔ API', 'text', 'پیش‌فرض https://edge.ippanel.com/v1'), sms_pattern_otp: T('sms', 'کد الگوی (Pattern) کد تأیید', 'text', 'در صورت خالی‌بودن، متن قالب ارسال می‌شود'), sms_pattern_otp_var: T('sms', 'نام متغیر کد در الگو', 'text', 'پیش‌فرض code'),
  sms_template_otp: T('sms', 'قالب پیامک کد تأیید', 'textarea', 'متغیرها: {code} {company}'), sms_template_status: T('sms', 'قالب پیامک تغییر وضعیت', 'textarea', '{name} {code} {status} {company}'), sms_template_interview: T('sms', 'قالب پیامک دعوت به مصاحبه', 'textarea', '{name} {date} {time} {location} {company}'),
  sms_template_submitted: T('sms', 'قالب پیامک ثبت درخواست', 'textarea', '{name} {code} {company}'), sms_template_test: T('sms', 'قالب پیامک یادآوری آزمون', 'textarea', '{name} {test} {company}'),
  sms_notify_status: T('sms', 'پیامک خودکار تغییر وضعیت به متقاضی (در صورت انتخاب HR)', 'bool'), sms_notify_submitted: T('sms', 'پیامک تأیید ثبت درخواست', 'bool'), sms_notify_hr_new: T('sms', 'پیامک پروندهٔ جدید به تیم HR', 'bool'), sms_hr_mobiles: T('sms', 'موبایل‌های تیم HR (با کاما)'),
  sms_notify_interview_reminder: T('sms', 'پیامک یادآوری مصاحبهٔ فردا', 'bool'), sms_notify_test_reminder: T('sms', 'پیامک یادآوری آزمون انجام‌نشده', 'bool'), sms_price: T('sms', 'هزینهٔ هر پیامک (ریال، برای گزارش)', 'number'),
  otp_length: T('sms', 'طول کد تأیید', 'number', '۴ تا ۸'), otp_ttl_minutes: T('sms', 'اعتبار کد (دقیقه)', 'number'), otp_max_attempts: T('sms', 'حداکثر تلاش برای هر کد', 'number'), otp_resend_seconds: T('sms', 'فاصلهٔ ارسال مجدد (ثانیه)', 'number'), otp_max_per_hour: T('sms', 'سقف ارسال کد برای هر شماره در ساعت', 'number'),
  otp_dev_show: T('sms', 'نمایش کد روی صفحه (فقط برای تست!)', 'bool', 'در محیط واقعی حتماً خاموش باشد'),
  login_max_attempts: T('security', 'حداکثر تلاش ناموفق ورود', 'number'), login_lock_minutes: T('security', 'مدت قفل پس از تلاش‌های ناموفق (دقیقه)', 'number'), session_days: T('security', 'مدت «مرا به خاطر بسپار» (روز)', 'number'),
  force_password_change: T('security', 'اجبار تغییر رمز در اولین ورود کاربران جدید', 'bool'), password_min_length: T('security', 'حداقل طول رمز عبور', 'number'), upload_max_mb: T('security', 'حداکثر حجم فایل بارگذاری (MB)', 'number'),
  primary_color: T('appearance', 'رنگ اصلی', 'color'), default_theme: T('appearance', 'پوستهٔ پیش‌فرض', 'select', '', { light: 'روشن', dark: 'تیره' }), sidebar_mode: T('appearance', 'حالت منوی کناری', 'select', '', { accordion: 'آکاردئونی', flat: 'ساده' }), sidebar_single: T('appearance', 'فقط یک گروه منو باز باشد', 'bool'), items_per_page: T('appearance', 'تعداد ردیف در هر صفحه', 'number'),
  notify_retry_max: T('notifications', 'حداکثر تلاش مجدد ارسال', 'number'), activity_keep_days: T('notifications', 'نگهداری لاگ فعالیت (روز)', 'number'),
  maintenance_mode: T('maintenance', 'حالت نگهداری', 'bool'), maintenance_message: T('maintenance', 'پیام حالت نگهداری', 'textarea'), maintenance_until: T('maintenance', 'تا زمان (نمایشی)'), maintenance_allow_ips: T('maintenance', 'IPهای مجاز در حالت نگهداری', 'textarea'),
  disk_alert_enabled: T('maintenance', 'هشدار فضای دیسک', 'bool'), disk_alert_min_mb: T('maintenance', 'حداقل فضای آزاد (MB)', 'number'), disk_alert_percent: T('maintenance', 'هشدار در درصد اشغال', 'number'), backup_keep: T('maintenance', 'تعداد پشتیبان‌های نگهداری‌شده', 'number'), backup_auto_type: T('maintenance', 'نوع پشتیبان خودکار', 'select', '', { db: 'فقط پایگاه داده', full: 'کامل (با فایل‌ها)' }),
  scheduler_mode: T('maintenance', 'اجرای کارهای زمان‌بندی‌شده', 'select', '', { internal: 'داخلی (خودکار)', cron: 'فقط cron بیرونی' }), cron_token: T('maintenance', 'توکن cron', 'internal'),
  demo_mode: T('system', 'حالت نمایشی (نمایش حساب‌های نمونه در صفحهٔ ورود)', 'bool'), app_version: T('system', 'نسخهٔ برنامه', 'internal'), app_updated_at: T('system', 'آخرین به‌روزرسانی', 'internal'), employee_code_prefix: T('system', 'پیشوند کد پرسنلی'), employee_code_next: T('system', 'کد پرسنلی بعدی', 'number'), dashboard_days: T('system', 'بازهٔ آمار داشبورد (روز)', 'number'),
  accent_palette: T('appearance', 'پالت رنگی', 'internal'), allowed_login_roles: T('security', 'نقش‌های مجاز به ورود با رمز', 'internal'), recruitment_allow_multiple: T('recruitment', 'چند پروندهٔ هم‌زمان برای یک متقاضی', 'bool'), recruitment_auto_archive_days: T('recruitment', 'بایگانی خودکار پرونده‌های بسته‌شده پس از (روز)', 'number'), assessment_time_limit: T('assessment', 'محدودیت زمان پیش‌فرض آزمون (دقیقه)', 'number'), sms_pattern_status: T('sms', 'کد الگوی تغییر وضعیت (اختیاری)', 'text')
};
const TABS = [
  { key: 'company', title: 'شرکت', icon: 'bi-building', keys: ['company_name', 'company_short_name', 'company_slogan', 'company_phone', 'company_email', 'company_website', 'company_city', 'company_address', 'company_intro', 'app_url', 'timezone_offset'] },
  { key: 'recruitment', title: 'استخدام', icon: 'bi-person-plus', keys: ['recruitment_open', 'recruitment_intro', 'recruitment_closed_text', 'recruitment_thanks_text', 'recruitment_declaration', 'recruitment_require_photo', 'recruitment_require_resume', 'recruitment_allow_edit_after_submit', 'recruitment_duplicate_check', 'recruitment_tracking_prefix', 'recruitment_form_code', 'recruitment_sla_days', 'recruitment_draft_days', 'recruitment_notify_hr_inapp'] },
  { key: 'assessment', title: 'آزمون', icon: 'bi-clipboard2-pulse', keys: ['assessment_required', 'assessment_auto_assign', 'assessment_form_code'] },
  { key: 'sms', title: 'پیامک و کد تأیید', icon: 'bi-chat-left-text', keys: ['sms_enabled', 'sms_provider', 'sms_api_key', 'sms_sender', 'sms_api_base', 'sms_pattern_otp', 'sms_pattern_otp_var', 'sms_template_otp', 'sms_template_submitted', 'sms_template_status', 'sms_template_interview', 'sms_template_test', 'sms_notify_submitted', 'sms_notify_status', 'sms_notify_interview_reminder', 'sms_notify_test_reminder', 'sms_notify_hr_new', 'sms_hr_mobiles', 'sms_price', 'otp_length', 'otp_ttl_minutes', 'otp_max_attempts', 'otp_resend_seconds', 'otp_max_per_hour', 'otp_dev_show'] },
  { key: 'security', title: 'امنیت', icon: 'bi-shield-lock', keys: ['login_max_attempts', 'login_lock_minutes', 'session_days', 'password_min_length', 'force_password_change', 'upload_max_mb'] },
  { key: 'appearance', title: 'ظاهر', icon: 'bi-palette', keys: ['primary_color', 'default_theme', 'sidebar_mode', 'sidebar_single', 'items_per_page'] },
  { key: 'maintenance', title: 'نگهداری', icon: 'bi-tools', keys: ['maintenance_mode', 'maintenance_message', 'maintenance_until', 'maintenance_allow_ips', 'disk_alert_enabled', 'disk_alert_min_mb', 'disk_alert_percent', 'backup_keep', 'backup_auto_type', 'scheduler_mode', 'activity_keep_days', 'demo_mode'] },
  { key: 'advanced', title: 'همهٔ تنظیمات', icon: 'bi-list-ul', keys: [] }
];
function meta(key) { return META[key] || { group: 'system', label: key, type: 'text', help: '' }; }
function isSecret(key) { return meta(key).type === 'secret'; }
function isInternal(key) { return meta(key).type === 'internal'; }
module.exports = { GROUPS, META, TABS, meta, isSecret, isInternal };
